name: Build recorder docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build_docker_image:
    name: "Build: ${{ matrix.name }}"
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MEP
            image_name: ${{ github.repository }}/mep
            base_image: ghcr.io/ryanvolz/holohub/rf-array-cuda-12-6:edge
            target: mep
          - name: VSWORD
            image_name: ${{ github.repository }}/vsword
            base_image: ghcr.io/ryanvolz/holohub/rf-array-cuda-12-2:edge
            target: vsword
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Log in to the upload container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ matrix.image_name }}
          tags: |
            type=schedule
            type=pep440,pattern=v{{version}}
            type=pep440,pattern=v{{major}}.{{minor}}
            type=pep440,pattern=v{{major}}
            type=raw,priority=710,value={{date 'YYYYMMDD-HHmm'}}
            type=edge
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          file: Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.DOCKER_REGISTRY }}/${{ matrix.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
