name: Build recorder docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build_docker_image:
    name: "Build: ${{ matrix.name }}"
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MEP
            dockerfile: Dockerfile.mep
            image_name: ${{ github.repository }}/mep
          - name: VSWORD
            dockerfile: Dockerfile.vsword
            image_name: ${{ github.repository }}/vsword
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Log in to the upload container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ matrix.image_name }}
          labels: |
            org.opencontainers.image.description=Holoscan MEP recorder
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=match,pattern=(v.*),group=1
            type=match,pattern=(v\d+.\d+).*,group=1
            type=match,pattern=(v\d+).*,group=1
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.DOCKER_REGISTRY }}/${{ matrix.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
